### ISSUE TITLE
MCA from pypi is outdated

### ISSUE THREAD

**Issue by j4n7** [esafak/mca#12]
Hi, I just want to let you know that install mca from pip gets you and outdated version that has no "expl_var" method. I manually downloaded your program from github and moved it inside site-packages folder and now I have the up-to-date version working.

Thank you very much for your program, im writing a program for my PhD and this is really useful.

Cheers

**Comment by esafak** [comment]
I'll push an update after fixing #11 Feel free to contribute to that discussion so we close it faster.
