### ISSUE TITLE
MCA throwing Memory Error 

### ISSUE THREAD

**Issue by alekyakumar** [esafak/mca#18]
I am trying to conduct MCA on my one-hot encoded matrix, but I am getting Memory Error when I execute the MCA command . I don't know whether it is because of the size of the data set, but the size I am using  currently is only 33% of the entire data set. 
The error occurs when Diagonal of the matrix is computed. I tried to do the mathematical operations separately , and I got the same error with "np.diag" as well. 

```
mca_ben = MCA(mca_dummies)

MemoryError                               Traceback (most recent call last)
<ipython-input-145-01aa9b49bc65> in <module>()
----> 1 mca_ben = MCA(mca_dummies)

C:\Users\Alekya Kumar\AppData\Roaming\Python\Python36\site-packages\mca.py in __init__(self, DF, cols, ncols, benzecri, TOL, sparse, approximate)
     64 
     65                 eps = finfo(float).eps
---> 66                 self.D_r = (diags if sparse else diag)(1/(eps + sqrt(self.r)))
     67                 self.D_c = diag(1/(eps + sqrt(self.c)))  # can't use diags here
     68                 Z_c = Z - outer(self.r, self.c)  # standardized residuals matrix

C:\Users\Public\Anaconda3\lib\site-packages\numpy\lib\twodim_base.py in diag(v, k)
    253     if len(s) == 1:
    254         n = s[0]+abs(k)
--> 255         res = zeros((n, n), v.dtype)
    256         if k >= 0:
    257             i = k

MemoryError: 



```

**Comment by esafak** [comment]
Try using https://github.com/MaxHalford/prince 
If you still run out of memory, upload data that makes it fail to somewhere like dropbox. Or better, write a function to generate random data similar to yours. How much memory and data do you have?
