### ISSUE TITLE
Improvements Suggestions

### ISSUE THREAD

**Issue by psygo** [esafak/mca#19]
Hello @esafak , I'm new to MCA so perhaps my comments won't be that precise -- or useful? :[].

There is a lot of potential for this library -- I don't know if that really interests you, but anyways...:

1. Could you reshape the function names and structure to emulate `sklearn`'s conventions? Creating `fit` and `predict` methods would really relieve the user of a lot of mathematical clutter. The `FactoMineR` library uses a similar convention to `sklearn`'s and has been very popular in `R`, I guess you could just transpile their structure.
2. When returning the transformed dataset, would it be possible to return the linear transformation matrix *with the names of the original columns on top*?
3. From what I understand so far, MCA does also calculate *inertia for each variable*, it would be nice to have a method that spits out a Pandas Series with the respective column names and inertias.
4. I'm not sure about this one but, when converting pandas `uint8` to numpy arrays using `X.values`, the calculations simply cannot be done. I had to manually convert the original pandas DataFrame to `float64` to get things going, which will be a huge memory hog for big datasets.
5. François Husson has published some tutorials on [MCA](https://youtu.be/gZ_7WWEVlTg) and CA on his channel, it would be nice to have links to them on the front page.

I know the implementations take a lot of time and effort to be programmed so if you need any financial aid, just place a Paypal link and I'll try to help.

**Comment by esafak** [comment]
My bottleneck is time, not money, so I invite you to submit a pull request implementing your suggestions.

Thank you for your enthusiasm.

**Comment by psygo** [comment]
Ah, I'll see what I can do, but, as I said, this is fairly new to me, so I don't know if I'll be able to submit anything worthwhile. And, just like you, time is also my bottleneck T.T .
