### ISSUE TITLE
Should number samples must be greater than reduced dimension value

### ISSUE THREAD

**Issue by bhisham123** [esafak/mca#20]
I am trying MCA with bag of words  dataset,  i am using following code 

ca = mca.MCA(pd.DataFrame(X_train))
new_x_train = ca.fs_r_sup(pd.DataFrame(X_train),  2000)
new_x_test = ca.fs_r_sup(pd.DataFrame(X_test), 2000)
print(new_x_train.shape)

where 
X_train.shape = (1400, 6906)
X_test.shape = (700, 6906)

Output, i am getting
new_x_train.shape = (1400, 1299) 

But output should be (1400, 2000)

Is it right to use MCA  for dimension reduction, with high dimensional data sets like bag of words?

**Comment by esafak** [comment]
Yes, I think it should be, same as for PCA. For a bag of words you could probably use regular PCA.
